name: Deploy Website

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Update and test server 1
    - name: Put server 1 in maintenance mode
      run: |
        sudo ufw deny 80
        sudo ufw deny 443

    - name: Deploy to server 1
      uses: appleboy/rsync-action@master
      with:
        args: -avz --delete --exclude='.git'
        src: ./
        dest: user@server1:/var/www/html/

    - name: Take server 1 out of maintenance mode
      run: |
        sudo ufw allow 80
        sudo ufw allow 443

    - name: Test server 1
      run: |
        response=$(curl -I server1.example.com | head -n 1 | cut -d$' ' -f2)
        if [[ $response -ne 200 ]]; then
          echo "Error: Server 1 returned status code $response"
          exit 1
        fi

    # Update and test server 2
    - name: Put server 2 in maintenance mode
      run: |
        sudo ufw deny 80
        sudo ufw deny 443

    - name: Deploy to server 2
      uses: appleboy/rsync-action@master
      with:
        args: -avz --delete --exclude='.git'
        src: ./
        dest: user@server2:/var/www/html/

    - name: Take server 2 out of maintenance mode
      run: |
        sudo ufw allow 80
        sudo ufw allow 443

    - name: Test server 2
      run: |
        response=$(curl -I server2.example.com | head -n 1 | cut -d$' ' -f2)
        if [[ $response -ne 200 ]]; then
          echo "Error: Server 2 returned status code $response"
          exit 1
        fi
